# Generated by Django 5.2.5 on 2025-09-22 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filamenttype_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='filament_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='core.filamenttype'),
        ),
    ]
